
services:
  mongodb:
    image: mongo:latest
    container_name: tts-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    networks:
      - tts-network

  mongo-express:
    image: mongo-express:latest
    container_name: tts-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
    depends_on:
      - mongodb
    networks:
      - tts-network

networks:
  tts-network:
    driver: bridge

volumes:
  mongodb_data: 